// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMJGe8uSnJLRpOfLfJMcbcfCzsyR4dSnE',
    appId: '1:254482251404:web:9ec249a9ccd79642c185a9',
    messagingSenderId: '254482251404',
    projectId: 'grocery-7c3f7',
    authDomain: 'grocery-7c3f7.firebaseapp.com',
    storageBucket: 'grocery-7c3f7.appspot.com',
    measurementId: 'G-YJE5F8MHJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWIYT7J5fiLo2Onw2rroXJqHZNovc4YH4',
    appId: '1:254482251404:android:6791c3bdd43d0fc2c185a9',
    messagingSenderId: '254482251404',
    projectId: 'grocery-7c3f7',
    storageBucket: 'grocery-7c3f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXeDbyohzYpJsUkgvNjKCpurtNRcZA4Zc',
    appId: '1:254482251404:ios:9b7fb8b291e2e78bc185a9',
    messagingSenderId: '254482251404',
    projectId: 'grocery-7c3f7',
    storageBucket: 'grocery-7c3f7.appspot.com',
    iosClientId: '254482251404-721cntlr0s32o8hi3atvijb7bh5om1iu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBlocTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXeDbyohzYpJsUkgvNjKCpurtNRcZA4Zc',
    appId: '1:254482251404:ios:9b7fb8b291e2e78bc185a9',
    messagingSenderId: '254482251404',
    projectId: 'grocery-7c3f7',
    storageBucket: 'grocery-7c3f7.appspot.com',
    iosClientId: '254482251404-721cntlr0s32o8hi3atvijb7bh5om1iu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBlocTutorial',
  );
}
